# Generated by Django 3.2.8 on 2021-11-18 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('password', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='securenote',
            name='email',
            field=models.CharField(default='nothing@gmail.com', max_length=40),
        ),
        migrations.AlterField(
            model_name='securecontacts',
            name='user_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='securenote',
            name='user_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
