# Generated by Django 3.2.8 on 2021-10-10 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_userdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='employee',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img/%y'),
        ),
    ]
