# Generated by Django 3.2.8 on 2021-11-17 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_employees_employee_of'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='employee_of',
            new_name='user',
        ),
    ]
