# Generated by Django 3.2.8 on 2021-11-17 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0004_rename_employee_of_employees_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='user',
        ),
        migrations.AddField(
            model_name='employees',
            name='employee_of',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
