# Generated by Django 3.2.8 on 2021-11-17 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_alter_employees_employee_of'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='employee_of',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
