# Generated by Django 3.2.8 on 2021-11-03 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetail',
            old_name='id_admin',
            new_name='is_admin',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='is_user',
        ),
    ]
