# Generated by Django 3.2.8 on 2021-11-04 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20211103_2150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='is_admin',
        ),
    ]
