# Generated by Django 3.2.8 on 2021-10-13 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ImageField(blank=True, null=True, upload_to='emp/')),
                ('reg_date', models.CharField(blank=True, max_length=11, null=True)),
                ('designation', models.CharField(blank=True, max_length=30, null=True)),
                ('salary_type', models.CharField(blank=True, max_length=7, null=True)),
                ('salary', models.IntegerField(blank=True, null=True)),
                ('salary_paid', models.IntegerField(blank=True, null=True)),
                ('salary_left', models.IntegerField(blank=True, null=True)),
                ('commission', models.IntegerField(blank=True, null=True)),
                ('cnic', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile', models.CharField(blank=True, max_length=12, null=True)),
                ('address', models.CharField(blank=True, max_length=150, null=True)),
                ('Bank_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('account_num', models.CharField(blank=True, max_length=30, null=True)),
                ('employee_of', models.IntegerField()),
            ],
        ),
    ]
