# Generated by Django 3.2.8 on 2021-10-15 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20211013_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='name',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='salary_type',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('weekly', 'Weekly'), ('daily', 'Daily')], max_length=7, null=True),
        ),
    ]
