# Generated by Django 3.2.8 on 2021-10-27 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20211015_0909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='Bank_Name',
        ),
        migrations.AddField(
            model_name='employees',
            name='blood',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='department',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='father_name',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='other_mobile',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='religion',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
