# Generated by Django 3.2.8 on 2021-10-28 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20211027_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='email',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
