# Generated by Django 3.2.8 on 2021-10-29 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_alter_employees_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='commission',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
