# Generated by Django 3.2.8 on 2021-10-30 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_alter_employees_commission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='salary_type',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
