# Generated by Django 3.2.8 on 2021-10-31 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_alter_employees_salary_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='cnic',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
