# Generated by Django 3.2.8 on 2021-10-18 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecureNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('encrypt', models.BinaryField()),
                ('key', models.BinaryField()),
                ('account_for', models.CharField(max_length=30)),
                ('letter', models.CharField(max_length=1)),
            ],
        ),
    ]
